name: First Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: First Job
        run: echo 'testing the first job'

        # For testing failed
        # run: exit 1
