name: Second Workflow

on:
  workflow_run:
    workflows: ["First Workflow"]
    types:
      - completed

jobs:
  run-if-success:
    runs-on: ubuntu-latest
    steps:
      - name: Second Job
        run: echo "This runs only if the first workflow succeeds"
