name: Second Workflow

on:
  push:
    branches:
      - main

jobs:
  run-if-success:
    # Check the result of the previous action pipeline
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Second Job
        run: echo "This runs only if the first workflow succeeds"
